# ---- Build stage ----
FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# ---- Runtime stage ----
FROM eclipse-temurin:17-jre
WORKDIR /app

# Copy the JAR built in the previous stage
COPY --from=build /app/target/*.jar app.jar

EXPOSE 5000
ENTRYPOINT ["java","-jar","app.jar"]
